/**
 * `generate types` — derive a typed entitlement-handle module from a config.
 *
 * Pure: extraction and rendering take their inputs as arguments; `cli.ts` owns
 * the IO (selector resolution, file writes). Grouping is data-driven off each
 * entitlement's `type` value, so new entitlement types flow through without a
 * CLI change. Output is deterministic — sorted, deduped, no timestamps — so a
 * committed generated file only changes when the Playbook's handles change.
 *
 * The emitted module is `as const` objects + literal unions rather than a TS
 * `enum`: erasable under `isolatedModules`/`erasableSyntaxOnly`, and the values
 * ARE the runtime handle strings `can()` / `gate()` / `checkEntitlement()`
 * take, so no mapping layer is needed.
 */

/** Entitlement handles grouped by their `type`, each list sorted + deduped. */
export type HandlesByType = Record<string, string[]>;

export interface HandlesCodegenResult {
  byType: HandlesByType;
  /** Flat sorted union of every handle across types. */
  handles: string[];
  /** The generated TypeScript module text. */
  ts: string;
}

/** Entitlements whose `type` is missing/blank group here (schema requires a
 * type, so this only fires on hand-authored configs). */
export const UNTYPED_GROUP = 'untyped';

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function nonEmptyString(value: unknown): string | null {
  return typeof value === 'string' && value.length > 0 ? value : null;
}

/** Group every entitlement handle in the config by its `type`. Entries without
 * a usable handle are skipped (validation, not codegen, owns that finding). */
export function extractEntitlementHandles(config: unknown): HandlesByType {
  if (!isRecord(config) || !Array.isArray(config.entitlements)) return {};
  const groups = new Map<string, Set<string>>();
  for (const entry of config.entitlements) {
    if (!isRecord(entry)) continue;
    const handle = nonEmptyString(entry.unique_handle) ?? nonEmptyString(entry.handle);
    if (!handle) continue;
    const type = nonEmptyString(entry.type) ?? UNTYPED_GROUP;
    const set = groups.get(type) ?? new Set<string>();
    set.add(handle);
    groups.set(type, set);
  }
  const byType: HandlesByType = {};
  for (const type of [...groups.keys()].sort()) {
    byType[type] = [...(groups.get(type) as Set<string>)].sort();
  }
  return byType;
}

const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

const quote = (s: string): string => `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;

/** Object-literal key: bare when a valid identifier, quoted otherwise (handles
 * may legally contain dots — HANDLE_PATTERN allows `[a-z0-9._]`). */
const key = (s: string): string => (IDENTIFIER.test(s) ? s : quote(s));

export interface RenderOptions {
  /** Human description of where the config came from (selector or file). */
  source: string;
  /** The exact command that reproduces this file — embedded in the header. */
  regenerate: string;
}

/** Render the generated TypeScript module. */
export function renderHandlesModule(byType: HandlesByType, opts: RenderOptions): string {
  const lines: string[] = [
    '// Generated by `revturbine generate types` — do not edit by hand.',
    `// Source: ${opts.source}`,
    '// Regenerate (rerun after any `launch` that changes entitlements):',
    `//   ${opts.regenerate}`,
    '',
    '/** Entitlement handles, namespaced by entitlement type. */',
  ];

  const types = Object.keys(byType);
  if (types.length === 0) {
    lines.push('export const Entitlements = {} as const;');
  } else {
    lines.push('export const Entitlements = {');
    for (const type of types) {
      lines.push(`  ${key(type)}: {`);
      for (const handle of byType[type]) {
        lines.push(`    ${key(handle)}: ${quote(handle)},`);
      }
      lines.push('  },');
    }
    lines.push('} as const;');
  }

  const flat = [...new Set(types.flatMap((t) => byType[t]))].sort();
  lines.push(
    '',
    '/** Every entitlement handle — the argument type for can() / gate() / checkEntitlement(). */',
  );
  if (flat.length === 0) {
    lines.push('export type EntitlementHandle = never;');
  } else {
    lines.push('export type EntitlementHandle =');
    flat.forEach((handle, i) => {
      lines.push(`  | ${quote(handle)}${i === flat.length - 1 ? ';' : ''}`);
    });
  }

  lines.push(
    '',
    '/** The entitlement-type namespaces present in this Playbook. */',
    'export type EntitlementTypeName = keyof typeof Entitlements;',
    '',
  );
  return lines.join('\n');
}

// ── Additional static-handle families (plan 174 TASK-11) ─────────────────────
//
// Every family a Playbook carries as authored strings gets a typed module
// section, so free-string call sites (plan targeting, segment refs, slot
// template filters, uiPathResolvers keys) can be handle-checked at compile
// time. Extraction is defensive over opaque records — validation, not codegen,
// owns malformed-config findings. Canonical *event names* have no config or
// snapshot source of truth yet; that family is a named follow-up, not emitted.

function collectStrings(values: Iterable<unknown>): string[] {
  const out = new Set<string>();
  for (const value of values) {
    const s = nonEmptyString(value);
    if (s) out.add(s);
  }
  return [...out].sort();
}

/** `plans[].unique_handle` (falling back to `handle` / `id` for hand-authored configs). */
export function extractPlanHandles(config: unknown): string[] {
  if (!isRecord(config) || !Array.isArray(config.plans)) return [];
  return collectStrings(
    config.plans.map((p) =>
      isRecord(p) ? (nonEmptyString(p.unique_handle) ?? nonEmptyString(p.handle) ?? p.id) : null,
    ),
  );
}

/** `segments[].handle` (falling back to `id`). */
export function extractSegmentHandles(config: unknown): string[] {
  if (!isRecord(config) || !Array.isArray(config.segments)) return [];
  return collectStrings(
    config.segments.map((s) => (isRecord(s) ? (nonEmptyString(s.handle) ?? s.id) : null)),
  );
}

/**
 * Surface-template ids: the `surface_templates` catalog plus every
 * `template_id` a payload surface actually references (inline
 * `placements[].payloads[].surfaces[]` and standalone
 * `placement_payloads[].surfaces[]`) — custom templates included.
 */
export function extractSurfaceTemplateIds(config: unknown): string[] {
  if (!isRecord(config)) return [];
  const ids: unknown[] = [];
  if (Array.isArray(config.surface_templates)) {
    for (const t of config.surface_templates) {
      if (isRecord(t)) ids.push(t.id ?? t.template_id);
    }
  }
  const surfacesOf = (payload: unknown): void => {
    if (!isRecord(payload) || !Array.isArray(payload.surfaces)) return;
    for (const surface of payload.surfaces) {
      if (isRecord(surface)) ids.push(surface.template_id);
    }
  };
  if (Array.isArray(config.placements)) {
    for (const placement of config.placements) {
      if (!isRecord(placement) || !Array.isArray(placement.payloads)) continue;
      for (const payload of placement.payloads) surfacesOf(payload);
    }
  }
  if (Array.isArray(config.placement_payloads)) {
    for (const payload of config.placement_payloads) surfacesOf(payload);
  }
  return collectStrings(ids);
}

/**
 * `content_ui_paths[].action_type` — the authored ui-path vocabulary, i.e.
 * exactly the key set `uiPathResolvers` must cover.
 */
export function extractUiPathActionTypes(config: unknown): string[] {
  if (!isRecord(config) || !Array.isArray(config.content_ui_paths)) return [];
  return collectStrings(
    config.content_ui_paths.map((p) => (isRecord(p) ? p.action_type : null)),
  );
}

function renderFlatFamily(
  lines: string[],
  opts: { doc: string; constName: string; typeName: string; values: string[] },
): void {
  lines.push('', `/** ${opts.doc} */`);
  if (opts.values.length === 0) {
    lines.push(`export const ${opts.constName} = {} as const;`);
    lines.push(`export type ${opts.typeName} = never;`);
    return;
  }
  lines.push(`export const ${opts.constName} = {`);
  for (const value of opts.values) {
    lines.push(`  ${key(value)}: ${quote(value)},`);
  }
  lines.push('} as const;');
  lines.push(`export type ${opts.typeName} =`);
  opts.values.forEach((value, i) => {
    lines.push(`  | ${quote(value)}${i === opts.values.length - 1 ? ';' : ''}`);
  });
}

export function generateHandleTypes(config: unknown, opts: RenderOptions): HandlesCodegenResult {
  const byType = extractEntitlementHandles(config);
  const handles = [...new Set(Object.values(byType).flat())].sort();

  const lines = [renderHandlesModule(byType, opts).trimEnd()];
  renderFlatFamily(lines, {
    doc: 'Plan handles — the values plan targeting and planHandle options take.',
    constName: 'Plans',
    typeName: 'PlanHandle',
    values: extractPlanHandles(config),
  });
  renderFlatFamily(lines, {
    doc: 'Segment handles.',
    constName: 'Segments',
    typeName: 'SegmentHandle',
    values: extractSegmentHandles(config),
  });
  renderFlatFamily(lines, {
    doc: 'Surface-template ids — catalog entries plus every template a payload references.',
    constName: 'SurfaceTemplates',
    typeName: 'SurfaceTemplateId',
    values: extractSurfaceTemplateIds(config),
  });
  renderFlatFamily(lines, {
    doc: 'Authored ui-path action types — exactly the key set uiPathResolvers must cover.',
    constName: 'UiPathActionTypes',
    typeName: 'UiPathActionType',
    values: extractUiPathActionTypes(config),
  });
  lines.push('');
  return { byType, handles, ts: lines.join('\n') };
}
