/**
 * `generate types` — derive a typed entitlement-handle module from a config.
 *
 * Pure: extraction and rendering take their inputs as arguments; `cli.ts` owns
 * the IO (selector resolution, file writes). Grouping is data-driven off each
 * entitlement's `type` value, so new entitlement types flow through without a
 * CLI change. Output is deterministic — sorted, deduped, no timestamps — so a
 * committed generated file only changes when the Playbook's handles change.
 *
 * The emitted module is `as const` objects + literal unions rather than a TS
 * `enum`: erasable under `isolatedModules`/`erasableSyntaxOnly`, and the values
 * ARE the runtime handle strings `can()` / `gate()` / `checkEntitlement()`
 * take, so no mapping layer is needed.
 */

/** Entitlement handles grouped by their `type`, each list sorted + deduped. */
export type HandlesByType = Record<string, string[]>;

export interface HandlesCodegenResult {
  byType: HandlesByType;
  /** Flat sorted union of every handle across types. */
  handles: string[];
  /** The generated TypeScript module text. */
  ts: string;
}

/** Entitlements whose `type` is missing/blank group here (schema requires a
 * type, so this only fires on hand-authored configs). */
export const UNTYPED_GROUP = 'untyped';

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function nonEmptyString(value: unknown): string | null {
  return typeof value === 'string' && value.length > 0 ? value : null;
}

/** Group every entitlement handle in the config by its `type`. Entries without
 * a usable handle are skipped (validation, not codegen, owns that finding). */
export function extractEntitlementHandles(config: unknown): HandlesByType {
  if (!isRecord(config) || !Array.isArray(config.entitlements)) return {};
  const groups = new Map<string, Set<string>>();
  for (const entry of config.entitlements) {
    if (!isRecord(entry)) continue;
    const handle = nonEmptyString(entry.unique_handle) ?? nonEmptyString(entry.handle);
    if (!handle) continue;
    const type = nonEmptyString(entry.type) ?? UNTYPED_GROUP;
    const set = groups.get(type) ?? new Set<string>();
    set.add(handle);
    groups.set(type, set);
  }
  const byType: HandlesByType = {};
  for (const type of [...groups.keys()].sort()) {
    byType[type] = [...(groups.get(type) as Set<string>)].sort();
  }
  return byType;
}

const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

const quote = (s: string): string => `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;

/** Object-literal key: bare when a valid identifier, quoted otherwise (handles
 * may legally contain dots — HANDLE_PATTERN allows `[a-z0-9._]`). */
const key = (s: string): string => (IDENTIFIER.test(s) ? s : quote(s));

export interface RenderOptions {
  /** Human description of where the config came from (selector or file). */
  source: string;
  /** The exact command that reproduces this file — embedded in the header. */
  regenerate: string;
}

/** Render the generated TypeScript module. */
export function renderHandlesModule(byType: HandlesByType, opts: RenderOptions): string {
  const lines: string[] = [
    '// Generated by `revturbine generate types` — do not edit by hand.',
    `// Source: ${opts.source}`,
    '// Regenerate (rerun after any `launch` that changes entitlements):',
    `//   ${opts.regenerate}`,
    '',
    '/** Entitlement handles, namespaced by entitlement type. */',
  ];

  const types = Object.keys(byType);
  if (types.length === 0) {
    lines.push('export const Entitlements = {} as const;');
  } else {
    lines.push('export const Entitlements = {');
    for (const type of types) {
      lines.push(`  ${key(type)}: {`);
      for (const handle of byType[type]) {
        lines.push(`    ${key(handle)}: ${quote(handle)},`);
      }
      lines.push('  },');
    }
    lines.push('} as const;');
  }

  const flat = [...new Set(types.flatMap((t) => byType[t]))].sort();
  lines.push(
    '',
    '/** Every entitlement handle — the argument type for can() / gate() / checkEntitlement(). */',
  );
  if (flat.length === 0) {
    lines.push('export type EntitlementHandle = never;');
  } else {
    lines.push('export type EntitlementHandle =');
    flat.forEach((handle, i) => {
      lines.push(`  | ${quote(handle)}${i === flat.length - 1 ? ';' : ''}`);
    });
  }

  lines.push(
    '',
    '/** The entitlement-type namespaces present in this Playbook. */',
    'export type EntitlementTypeName = keyof typeof Entitlements;',
    '',
  );
  return lines.join('\n');
}

export function generateHandleTypes(config: unknown, opts: RenderOptions): HandlesCodegenResult {
  const byType = extractEntitlementHandles(config);
  const handles = [...new Set(Object.values(byType).flat())].sort();
  return { byType, handles, ts: renderHandlesModule(byType, opts) };
}
